image: intellectstorm/ruby-postgres-npm

stages:
  - build
  - test

.base:
  image: intellectstorm/ruby-postgres-npm
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - apt-cache/
      - vendor/
    policy: pull
  before_script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor

.base_db:
  extends: .base
  services:
    - postgres:16
  variables:
    RAILS_ENV: test
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -qq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -yqq nodejs
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor

install:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
  script:
    - bundle install -j $(nproc)

rubocop:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor
    policy: pull
  script:
    - bundle install
    - bundle exec rubocop

rspec:
  stage: test
  services:
    - postgres:16
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
    RAILS_ENV: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull
  script:
    - npm install
    - bundle install
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake assets:precompile
    - bundle exec rspec
  coverage: '/\(\d+.\d+\%\) covered/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml

brakeman:
  stage: test
  allow_failure: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor
    policy: pull
  artifacts:
    name: brakeman_report
    when: always
    paths:
      - brakeman/
  script:
    - bundle install
    - bundle exec brakeman --format html -o brakeman/index.html

bundle_audit:
  stage: test
  allow_failure: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull
  script:
    - bundle install
    - bundle exec bundle audit check --update
