require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/electors', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Elector. As you add validations to Elector, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Elector.create! valid_attributes
      get electors_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      elector = Elector.create! valid_attributes
      get elector_url(elector)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_elector_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      elector = Elector.create! valid_attributes
      get edit_elector_url(elector)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Elector' do
        expect do
          post electors_url, params: { elector: valid_attributes }
        end.to change(Elector, :count).by(1)
      end

      it 'redirects to the created elector' do
        post electors_url, params: { elector: valid_attributes }
        expect(response).to redirect_to(elector_url(Elector.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Elector' do
        expect do
          post electors_url, params: { elector: invalid_attributes }
        end.not_to change(Elector, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post electors_url, params: { elector: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested elector' do
        elector = Elector.create! valid_attributes
        patch elector_url(elector), params: { elector: new_attributes }
        elector.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the elector' do
        elector = Elector.create! valid_attributes
        patch elector_url(elector), params: { elector: new_attributes }
        elector.reload
        expect(response).to redirect_to(elector_url(elector))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        elector = Elector.create! valid_attributes
        patch elector_url(elector), params: { elector: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested elector' do
      elector = Elector.create! valid_attributes
      expect do
        delete elector_url(elector)
      end.to change(Elector, :count).by(-1)
    end

    it 'redirects to the electors list' do
      elector = Elector.create! valid_attributes
      delete elector_url(elector)
      expect(response).to redirect_to(electors_url)
    end
  end
end
